-- CreateTable
CREATE TABLE "estudiantes" (
    "aluctr" VARCHAR(50) NOT NULL,
    "aluapp" VARCHAR(50),
    "aluapm" VARCHAR(50),
    "alunom" VARCHAR(100),
    "alusex" SMALLINT,
    "alunac" DATE,
    "alulna" VARCHAR(5),
    "alurfc" VARCHAR(13),
    "alucur" VARCHAR(18),
    "aluesc" INTEGER,
    "aluescpd" INTEGER,
    "aluescpa" INTEGER,
    "aluegr" SMALLINT,
    "aluare" SMALLINT,
    "aluescp" SMALLINT,
    "alucll" VARCHAR(100),
    "alunum" VARCHAR(10),
    "alucol" VARCHAR(100),
    "alucpo" INTEGER,
    "alumun" INTEGER,
    "aluciu" VARCHAR(100),
    "alute1" VARCHAR(15),
    "alute2" VARCHAR(15),
    "alumai" VARCHAR(100),
    "alumaii" VARCHAR(100),
    "alusme" INTEGER,
    "alusmei" VARCHAR(100),
    "alusmea" VARCHAR(100),
    "alutsa" VARCHAR(10),
    "alueci" INTEGER,
    "alupad" VARCHAR(100),
    "alumad" VARCHAR(100),
    "alupadv" TEXT,
    "alumadv" TEXT,
    "alupadt" VARCHAR(15),
    "alumadt" VARCHAR(15),
    "alutno" VARCHAR(100),
    "alutcl" VARCHAR(100),
    "alutnu" VARCHAR(10),
    "alutco" VARCHAR(100),
    "alutcp" INTEGER,
    "alutmu" INTEGER,
    "alutci" VARCHAR(100),
    "alutte1" VARCHAR(15),
    "alutte2" VARCHAR(15),
    "alutmai" VARCHAR(100),
    "alufac" VARCHAR(100),
    "alutwi" VARCHAR(100),
    "alutce" TEXT,
    "alutra" INTEGER,
    "alupas" VARCHAR(64),
    "alupasc" TEXT,
    "aluseg" VARCHAR(15),
    "alulexp" TEXT,
    "alulemp" INTEGER,
    "alulare" INTEGER,
    "alulfde" DATE,
    "alulfha" DATE,
    "tbecve" SMALLINT,
    "aluest" INTEGER,
    "alupes" DECIMAL(8,2),
    "gincve" INTEGER,
    "lincve" INTEGER,
    "aluoest" SMALLINT,
    "aluotra" SMALLINT,
    "alutinl" SMALLINT,
    "alutpot" SMALLINT,
    "alutsec" SMALLINT,
    "aluteotr" TEXT,
    "alutecll" VARCHAR(100),
    "alutenum" VARCHAR(10),
    "alutecol" VARCHAR(100),
    "aluteciu" VARCHAR(100),
    "alutecpo" INTEGER,
    "alutemun" INTEGER,
    "alutetel" VARCHAR(15),
    "alutepto" VARCHAR(50),
    "aluteanp" DATE,
    "aluteing" DECIMAL(10,2),
    "alupexani" SMALLINT,
    "alupegel" SMALLINT,
    "aluptoefl" SMALLINT,
    "discve" SMALLINT,
    "alucen" SMALLINT,
    "aluale" TEXT,
    "alupsi" TEXT,
    "aluteotrt" TEXT,
    "aludch" TEXT,
    "cve" INTEGER,
    "merida" INTEGER,

    CONSTRAINT "estudiantes_pkey" PRIMARY KEY ("aluctr")
);

-- CreateTable
CREATE TABLE "authStudents" (
    "id" SERIAL NOT NULL,
    "matricula" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "nombreCompleto" TEXT NOT NULL,
    "telefono" TEXT NOT NULL,
    "isVerified" BOOLEAN NOT NULL DEFAULT false,
    "smsCode" TEXT,

    CONSTRAINT "authStudents_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "authStudents_matricula_key" ON "authStudents"("matricula");
